import "@/styles/globals.css";

// import { GeistSans } from "geist/font/sans";
// import { type Metadata } from "next";

// import { TRPCReactProvider } from "@/trpc/react";

// import {
//   ClerkProvider,
// } from '@clerk/nextjs'

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <ClerkProvider>
//         <html lang="en" className={`${GeistSans.variable}`}>
//           <body>
//             <TRPCReactProvider>{children}</TRPCReactProvider>
//           </body>
//         </html>
//     </ClerkProvider>
//   );
// }

// RootLayout.tsx

import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import { GeistSans } from 'geist/font/sans';
import { TRPCReactProvider } from '@/trpc/react';
// import './globals.css';

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>

          {/* TODO: this part for extra */}
          {/* <header>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn> */}
          {/* </header> */}
          {/* TODO: */}
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}

